apiVersion: autoscale/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: myapp
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: utilization
          averageUtilization: 70