apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
spec:
  securityContext:
    runAsUser: 1001  # setting to run as non-root user
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
        name: nginx-port
      securityContext:
        runAsUser: 0 
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: nginx-logs 
          mountPath: /var/log/nginx
  
  volumes:
    - name: nginx-logs
      emptyDir: {}